
name: Publish package
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: echo "run tests"

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
      ##### create .npmrc file
      # //registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}
      # registry=https://registry.npmjs.org/
      # always-auth=true

      - run: yarn

      - run: echo github.ref ${{ github.ref }}
      - run: echo github.event.release.tag_name ${{ github.event.release.tag_name }}
      
      - run: echo $GITHUB_TAG

      - name: Dump gh.event.release
        run: echo "$JOB_CONTEXT"
        env:
          JOB_CONTEXT: ${{ toJson(github.event.release) }}
        
      - run: echo ${{ github.event }}
      - name: Dump gh.event
        run: echo "$JOB_CONTEXT"
        env:
          JOB_CONTEXT: ${{ toJson(github.event) }}

      - run: cat package.json
      # - run: yarn publish

        # env:
        #   NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
